"""Create Reviews model

Revision ID: 43e397060daa
Revises: 
Create Date: 2024-04-03 22:46:05.113472

"""
import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43e397060daa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.VARCHAR(length=64), nullable=True),
    sa.Column('external_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('review_body', mysql.TEXT(), nullable=True),
    sa.Column('rating_number', mysql.SMALLINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('author', sa.VARCHAR(length=192), nullable=True),
    sa.Column('post_date', sa.DATE(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code', 'external_id', name='unique_product_code_and_external_id')
    )
    op.create_index(op.f('ix_reviews_external_id'), 'reviews', ['external_id'], unique=False)
    op.create_index(op.f('ix_reviews_product_code'), 'reviews', ['product_code'], unique=False)
    op.create_index(op.f('ix_reviews_updated_at'), 'reviews', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_updated_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_product_code'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_external_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
